GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/61bef41feab98beeddb102ee

###

DELETE http://localhost:3001/api/persons/61bf1ee16af4ba2fea1fa130

###

POST http://localhost:3001/api/persons
content-type: application/json

    {
      "name": "Audrius1",
      "number": "44422"
    }

###

PUT http://localhost:3001/api/persons/61bef41feab98beeddb102ee
Content-Type: application/json

  {
    "number": "123-456"
  }